/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type AttributeType = 'boolean' | 'number' | 'text'

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>

export type Numeric = ColumnType<string, number | string, number | string>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Account {
	access_token: string | null
	access_token_expires_at: Timestamp | null
	account_id: string
	created_at: Generated<Timestamp>
	id: Generated<string>
	id_token: string | null
	issuer: string
	password: string | null
	provider_id: string
	refresh_token: string | null
	refresh_token_expires_at: Timestamp | null
	scope: string | null
	updated_at: Generated<Timestamp>
	user_id: string
}

export interface Attribute {
	id: Generated<string>
	name: string
	type: AttributeType
	user: string
}

export interface AttributeValue {
	attribute: string
	id: Generated<string>
	item: string
	value_boolean: boolean | null
	value_number: Numeric | null
	value_text: string | null
}

export interface Category {
	created_at: Generated<Timestamp>
	description: Generated<string>
	id: Generated<string>
	image: string | null
	name: string
	slug: string
	updated_at: Generated<Timestamp>
	user: string
}

export interface CategoryAttribute {
	attribute: string
	category: string
}

export interface CategoryItem {
	category: string
	item: string
}

export interface Item {
	created_at: Generated<Timestamp>
	description: Generated<string>
	id: Generated<string>
	image: string | null
	name: string
	updated_at: Generated<Timestamp>
	user: string
}

export interface Review {
	comment: Generated<string>
	created_at: Generated<Timestamp>
	id: Generated<string>
	item: string
	rating: number
	updated_at: Generated<Timestamp>
	user: string
}

export interface Session {
	created_at: Generated<Timestamp>
	expires_at: Timestamp
	id: Generated<string>
	impersonated_by: string | null
	ip_address: string | null
	token: string
	updated_at: Generated<Timestamp>
	user_agent: string | null
	user_id: string
}

export interface User {
	ban_expires: Timestamp | null
	ban_reason: string | null
	banned: boolean | null
	created_at: Generated<Timestamp>
	display_username: string | null
	email: string
	email_verified: Generated<boolean>
	id: Generated<string>
	image: string | null
	name: string
	role: string | null
	updated_at: Generated<Timestamp>
	username: string | null
}

export interface Verification {
	created_at: Generated<Timestamp>
	expires_at: Timestamp
	id: Generated<string>
	identifier: string
	updated_at: Generated<Timestamp>
	value: string
}

export interface DB {
	accounts: Account
	attribute_values: AttributeValue
	attributes: Attribute
	categories: Category
	category_attributes: CategoryAttribute
	category_items: CategoryItem
	items: Item
	reviews: Review
	sessions: Session
	users: User
	verifications: Verification
}
